### ISSUE TITLE
Congratulations 

### ISSUE THREAD

**Issue by flora077** [lixiaoyu2000/FastPoly#1]
Congratulations on releasing a new algorithm. Is this algorithm implemented in Python or C++? I've been having a headache lately trying to translate Poly-mot into C++.

**Comment by lixiaoyu2000** [comment]
Hi, thanks, we implement Fast-Poly only by Python.

**Comment by lixiaoyu2000** [comment]
Thanks, good luck!

**Comment by johannes-tum** [comment]
Also congratulations from my side and I cross finger that it gets accepted! 
Can you already estimate when the code will be released? At least roughly? Assuming that you get accepted.

**Comment by lixiaoyu2000** [comment]
@johannes-tum Hi, thank you for your interest in Fast-Poly! We plan to open-source the code in June or July. The idea behind Fast-Poly is simple and efficient. You can reproduce our results using our [paper ](https://arxiv.org/abs/2403.13443) and the [Poly-MOT](https://github.com/lixiaoyu2000/Poly-MOT) code. We welcome your feedback and hope you find Fast-Poly useful.

**Comment by moonsonK** [comment]
大佬，预计什么时候开源代码呀

**Comment by lixiaoyu2000** [comment]
Hi, we expect to open source the code at the end of August and are currently undergoing the first phase of rebuttal. Additionally, we expect to publish a revised version of our article in late July.

**Comment by dongyu728** [comment]
大佬，9月啦，快来开源啦

**Comment by zywvvd** [comment]
9月催更 +1

**Comment by lu-zilong** [comment]
同来催更^_^

**Comment by wanglumeng** [comment]
急

**Comment by lixiaoyu2000** [comment]
Thank you very much for your attention. We plan to release our code within one to two weeks after the final result of the article is decided. The article is currently in the pending stage.

**Comment by lixiaoyu2000** [comment]
We have released our code :blush:. This issue will be closed.
