### ISSUE TITLE
Question about computing track scroe

### ISSUE THREAD

**Issue by golnazou** [lixiaoyu2000/FastPoly#5]
Hi,

Thanks for sharing your impressive work!
Could you please explain the methodology and how you calculate tracking score in here: https://github.com/lixiaoyu2000/FastPoly/blob/main/tracking/nusc_score_manage.py

Thanks,
Golnaz Habibi

**Comment by lixiaoyu2000** [comment]
Hi, please check out the paper's Section III.C ([_Densification_](https://arxiv.org/pdf/2403.13443)). Your mentioned codes are aligned with the _Confidence-Count Mixed Lifecycle_ subsection.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
